# Site Settings
title:               Manifest's Blog
tagline:             The place where the fun starts
description:
baseurl:             #"/PersonalBlog"
url:                 #"https://robqiao.github.io"
github:	            		
  url:               #"https://github.com/robqiao/PersonalBlog"
author:		     	
  name:              "Robert Qiao"
  email:             "robert.qiao@flinders.edu.au"
  twitter:           "robqiao"
  instagram:         #""
  facebook:          #""
  github:            "robqiao"
  linkedin:          "robqiao"
navigation:
- title: About Us
  url: /aboutus
- title: News
  url: /announcements
- title: Blogs
  url: /blogs
- title: Contact Us
  url: /contactus

paginate:            5
disqus:              "robqiao"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
