# Site Settings
title:               Manifesto's Blog
tagline:             The place where the fun starts
description:
collections:
  announcements:
    output:           true
    permalink:        /:categories/:title/
  downloads:
    output:           true
    permalink:        /:categories/:title/
baseurl:             "/PersonalBlog"
url:                 "https://robqiao.github.io"
github:	            		
  url:               "https://github.com/manifestoso/PersonalBlog"
author:		     	
  name:              "Robert Qiao"
  email:             "robert.qiao@flinders.edu.au"
  twitter:           "robqiao"
  instagram:         #""
  facebook:          #""
  github:            "manifestoso"
  linkedin:          "robqiao"
navigation:
- title: About Us
  url: /aboutus
- title: News
  url: /announcements
- title: Blogs
  url: /blogs
- title: Downloads
  url: /downloads
- title: Contact Us
  url: /contactus

paginate:            5
disqus:              "robqiao"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:	         none 
plugins:             [jekyll-paginate]
